##################### Trigger Channels ##########################

dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=0,  ADDR=0,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=1,  ADDR=1,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=2,  ADDR=2,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=3,  ADDR=3,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=4,  ADDR=4,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=5,  ADDR=5,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=6,  ADDR=6,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=7,  ADDR=7,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=8,  ADDR=8,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=9,  ADDR=9,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=10, ADDR=10, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=11, ADDR=11, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=12, ADDR=12, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=13, ADDR=13, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=14, ADDR=14, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=15, ADDR=15, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=16, ADDR=16, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=17, ADDR=17, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=18, ADDR=18, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=19, ADDR=19, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=20, ADDR=20, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=21, ADDR=21, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=22, ADDR=22, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=23, ADDR=23, TIMEOUT=1")

