##################### Trigger Channels ##########################

dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=0,  ADDR=0,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=1,  ADDR=1,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=2,  ADDR=2,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=3,  ADDR=3,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=4,  ADDR=4,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=5,  ADDR=5,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=6,  ADDR=6,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=7,  ADDR=7,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=8,  ADDR=8,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=9,  ADDR=9,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=10, ADDR=10, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=11, ADDR=11, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=12, ADDR=12, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=13, ADDR=13, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=14, ADDR=14, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=15, ADDR=15, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=16, ADDR=16, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=17, ADDR=17, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=18, ADDR=18, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=19, ADDR=19, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=20, ADDR=20, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=21, ADDR=21, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=22, ADDR=22, TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER, TRIGGER_CHAN=23, ADDR=23, TIMEOUT=1")

# Second instance of the TRIGGER module

dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=0,  ADDR=24,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=1,  ADDR=25,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=2,  ADDR=26,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=3,  ADDR=27,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=4,  ADDR=28,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=5,  ADDR=29,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=6,  ADDR=30,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=7,  ADDR=31,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=8,  ADDR=32,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=9,  ADDR=33,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=10, ADDR=34,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=11, ADDR=35,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=12, ADDR=36,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=13, ADDR=37,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=14, ADDR=38,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=15, ADDR=39,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=16, ADDR=40,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=17, ADDR=41,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=18, ADDR=42,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=19, ADDR=43,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=20, ADDR=44,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=21, ADDR=45,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=22, ADDR=46,  TIMEOUT=1")
dbLoadRecords("${TOP}/db/FOFBTrigger.template", "P=${P}, R=${R}, PORT=$(PORT), TRIGGER_NAME=TRIGGER_PM, TRIGGER_CHAN=23, ADDR=47,  TIMEOUT=1")
